import { SceneProject } from './types';

/**
 * Code Generation & Multi-Target Compiler Engine
 * Adheres strictly to OpenSVG Feature Engineering Rules E5, E6, E7, E9
 */

/**
 * Sanitizes arbitrary strings to safe identifier names (Rule E6 & E7)
 */
export function sanitizeIdentifier(name: string, fallbackPrefix: string = 'node'): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_]/g, '_');
  if (/^[0-9]/.test(cleaned)) {
    return `${fallbackPrefix}_${cleaned}`;
  }
  return cleaned || `${fallbackPrefix}_${Date.now()}`;
}

/**
 * Compiles a SceneProject into production-ready React + Framer Motion component code (Rule E5, E6, E7).
 */
export function generateReactFramerMotionCode(project: SceneProject): string {
  const componentName = sanitizeIdentifier(project.name || 'MotionGraphic', 'MotionScene');
  const width = project.rootFrame.width || 600;
  const height = project.rootFrame.height || 400;
  const bg = project.rootFrame.fill || '#ffffff';

  const nodeElements: string[] = [];

  for (const id of project.nodeOrder) {
    const node = project.nodes[id];
    if (!node || !node.visible) continue;

    const safeId = sanitizeIdentifier(node.name || node.id);

    // Build keyframes for motion.div
    const animateProps: Record<string, any[]> = {};
    const times: number[] = [];

    if (node.tracks && node.tracks.length > 0) {
      for (const track of node.tracks) {
        if (track.keyframes.length > 0) {
          const propKey = track.property === 'borderRadius' ? 'borderRadius' : track.property;
          animateProps[propKey] = track.keyframes.map((k) => k.value);
          if (times.length === 0) {
            times.push(...track.keyframes.map((k) => parseFloat((k.time / project.duration).toFixed(3))));
          }
        }
      }
    }

    const hasAnimation = Object.keys(animateProps).length > 0;
    const animateString = hasAnimation
      ? JSON.stringify(animateProps)
      : JSON.stringify({
          x: node.x,
          y: node.y,
          rotate: node.rotation || 0,
          scaleX: node.scaleX ?? 1,
          scaleY: node.scaleY ?? 1,
          opacity: node.opacity ?? 1
        });

    const transitionString = hasAnimation
      ? JSON.stringify({
          duration: project.duration,
          repeat: Infinity,
          ease: 'easeInOut',
          times: times.length > 0 ? times : undefined
        })
      : '{}';

    const baseStyle = {
      position: 'absolute',
      width: `${node.width}px`,
      height: `${node.height}px`,
      backgroundColor: node.fill || '#3b82f6',
      borderRadius: node.type === 'circle' ? '50%' : `${node.borderRadius || 0}px`,
      border: node.stroke ? `${node.strokeWidth || 1}px solid ${node.stroke}` : undefined
    };

    nodeElements.push(
      `      {/* Node: ${safeId} */}\n` +
      `      <motion.div\n` +
      `        style={{\n` +
      Object.entries(baseStyle)
        .filter(([_, v]) => v !== undefined)
        .map(([k, v]) => `          ${k}: '${v}',`)
        .join('\n') +
      `\n        }}\n` +
      `        animate={${animateString}}\n` +
      `        transition={${transitionString}}\n` +
      `      />`
    );
  }

  return [
    "import React from 'react';",
    "import { motion } from 'framer-motion';",
    "",
    "/**",
    " * Auto-generated by OpenSVG Motion Studio",
    ` * Project: ${project.name} (${width}x${height}, ${project.duration}s @ ${project.fps}fps)`,
    " */",
    `export const ${componentName}: React.FC<{ className?: string }> = ({ className }) => {`,
    "  return (",
    "    <div",
    "      className={className}",
    "      style={{",
    "        position: 'relative',",
    `        width: '${width}px',`,
    `        height: '${height}px',`,
    `        backgroundColor: '${bg}',`,
    "        overflow: 'hidden'",
    "      }}",
    "    >",
    nodeElements.join('\n\n'),
    "    </div>",
    "  );",
    "};",
    "",
    `export default ${componentName};`,
    ""
  ].join('\n');
}

/**
 * Compiles a SceneProject into a self-contained zero-dependency HTML5 Embed Bundle (Rule E9).
 */
export function generateStandaloneHtmlBundle(project: SceneProject): string {
  const jsonString = JSON.stringify(project).replace(/</g, '\\u003c');
  const width = project.rootFrame.width || 600;
  const height = project.rootFrame.height || 400;

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0" />',
    `  <title>${project.name || 'OpenSVG Animation'}</title>`,
    '  <style>',
    '    body { margin: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; background: #0f172a; font-family: sans-serif; color: #f8fafc; }',
    `    .stage { position: relative; width: ${width}px; height: ${height}px; background: ${project.rootFrame.fill || '#fff'}; box-shadow: 0 25px 50px -12px rgba(0,0,0,0.5); border-radius: 8px; overflow: hidden; }`,
    '    canvas { width: 100%; height: 100%; display: block; }',
    '    .controls { margin-top: 16px; display: flex; align-items: center; gap: 12px; }',
    '    button { background: #2563eb; color: #fff; border: none; padding: 8px 16px; border-radius: 6px; cursor: pointer; font-weight: bold; }',
    '    input[type=range] { width: 240px; cursor: pointer; }',
    '  </style>',
    '</head>',
    '<body>',
    '  <div class="stage">',
    `    <canvas id="cvs" width="${width * 2}" height="${height * 2}"></canvas>`,
    '  </div>',
    '  <div class="controls">',
    '    <button id="btnPlay">Pause</button>',
    `    <input type="range" id="scrubber" min="0" max="${project.duration}" step="0.01" value="0" />`,
    '    <span id="time">0.00s</span>',
    '  </div>',
    '  <script>',
    `    const project = ${jsonString};`,
    "    const canvas = document.getElementById('cvs');",
    "    const ctx = canvas.getContext('2d');",
    "    const btnPlay = document.getElementById('btnPlay');",
    "    const scrubber = document.getElementById('scrubber');",
    "    const timeLabel = document.getElementById('time');",
    "",
    "    let isPlaying = true;",
    "    let currentTime = 0;",
    "    let lastTime = performance.now();",
    "",
    "    function render(t) {",
    "      ctx.clearRect(0, 0, canvas.width, canvas.height);",
    "      ctx.save();",
    "      ctx.scale(2, 2);",
    "      ctx.fillStyle = project.rootFrame.fill || '#ffffff';",
    `      ctx.fillRect(0, 0, ${width}, ${height});`,
    "",
    "      for (const id of project.nodeOrder) {",
    "        const node = project.nodes[id];",
    "        if (!node || !node.visible) continue;",
    "        ctx.save();",
    "        ctx.fillStyle = node.fill || '#3b82f6';",
    "        ctx.fillRect(node.x, node.y, node.width, node.height);",
    "        ctx.restore();",
    "      }",
    "      ctx.restore();",
    "    }",
    "",
    "    function loop(now) {",
    "      const dt = (now - lastTime) / 1000;",
    "      lastTime = now;",
    "      if (isPlaying) {",
    "        currentTime = (currentTime + dt) % project.duration;",
    "        scrubber.value = currentTime;",
    "        timeLabel.textContent = currentTime.toFixed(2) + 's';",
    "      }",
    "      render(currentTime);",
    "      requestAnimationFrame(loop);",
    "    }",
    "    requestAnimationFrame(loop);",
    "",
    "    btnPlay.onclick = () => {",
    "      isPlaying = !isPlaying;",
    "      btnPlay.textContent = isPlaying ? 'Pause' : 'Play';",
    "    };",
    "    scrubber.oninput = (e) => {",
    "      currentTime = parseFloat(e.target.value);",
    "      timeLabel.textContent = currentTime.toFixed(2) + 's';",
    "    };",
    "  </script>",
    '</body>',
    '</html>'
  ].join('\n');
}
